services:
  3dgs-mcmc:
    container_name: 3dgs-mcmc
    image: gitlab-int.nlr.nl:5050/dang/3dgs-mcmc:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /home/dang/git/3dgs-mcmc/src:/workspace/3dgs-mcmc
      - /home/dang/data:/workspace/data
      - /home/dang/output:/workspace/output
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute,utility,graphics]

